version: '3'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - mongo-network
    volumes:
     - mongo-data:/data/db
  mongo-exp:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-network
volumes:
  mongo-data:
   driver: local
networks:
  mongo-network:
      external: true